### ISSUE TITLE
changes to readme

### ISSUE THREAD

**Issue by andrewchambers** [oriansj/mes-m2#18]
I did a bootstrap using stage0-posix and had a few difficulties.

- The readme did not mention the env vars MES_ARENA , MES_MAX_ARENA, MES_STACK. They seemed necessary.

- The correct command for mes-m2 was:

```
MES_ARENA=20000000
MES_MAX_ARENA=20000000
MES_STACK=6000000
export MES_ARENA  MES_MAX_ARENA MES_STACK
$ ./bin/mes --no-auto-compile -L ../nyacc-1.00.2/module/  -e main scripts/mescc.scm -I include -v -S scaffold/exit-42.c
parsing: input
compiling: input
    :main
dumping: exit-42.s
M1: functions
    :main
M1: globals
```
(This differs because -L module was removed)

- The correct command for guile was:
```
guile --no-auto-compile -L ../nyacc-1.00.2/module/ -L module -e main scripts/mescc.scm -I include -v -S scaffold/exit-42.c
```

(This differs because it explains nyacc must be added to the module path)

**Comment by oriansj** [comment]
Thank you.

Changed
