### ISSUE TITLE
Making mescc work on slow_lisp

### ISSUE THREAD

**Issue by fosslinux** [oriansj/mes-m2#4]
I know @oriansj probably already knows all this but just documenting it.

From just removing stuff out of mescc.scm to try to make it "run", I've found the following things still need to be added to the slow_lisp branch to make it work:

- [ ] Modules support (define-module, use-module, mes-use-module)
- [x] `cond-expand` support https://www.gnu.org/software/mit-scheme/documentation/mit-scheme-ref/cond_002dexpand-_0028SRFI-0_0029.html
- [x] `getenv` support
- [ ] when (being a scheme n00b I have no idea what it is)

Haven't investigated much further yet but it seems to hang.

**Comment by oriansj** [comment]
well the good news is cond-expand is done via define-macro and currently works entirely in scheme so that doesn't need to be implemented.
and getenv is now working, setenv isn't yet

and I might end up not supporting mes-use-module if I do use-module correctly.

**Comment by fosslinux** [comment]
This hang is also actually a REPL loop from mes-m2 due to the .scm file exiting. It's correct behavior.

**Comment by oriansj** [comment]
recent work by janneke has solved this issue for us.
